Typo in DAE Scalar Descriptions
CURENT/andes pull request #517
Opened 2024-03-07 22:19 UTC by weigao-123

Typo in DAE Scalar Description table.

2024-03-07 22:31 UTC, jinningwang requested changes
https://github.com/CURENT/andes/blob/f955c3e46ab92d33a4373b0ed989e67059bb090c/andes/variables/dae.py#L313-L321

Given this code, I feel m is The number of algebraic variables/equations, and n is The number of state variables/equations.

Besides, would you mind changing the target branch from ``CURENT:master`` to ``CURENT:develop``? This helps us follow a better version control manner.

2024-03-07 22:35 UTC, weigao-123 commented
Yes, you are correct. I will change it, thank you!

2024-03-07 22:40 UTC, jinningwang approved these changes

2024-03-08 01:27 UTC, jinningwang approved these changes

2024-03-08 12:56 UTC, merged